### ISSUE TITLE
Error detecting GenInfo Identifier's in newer GenBank files

### ISSUE THREAD

**Issue by twbattaglia** [capsid/capsid-pipeline#11]
I am following the directions for adding viral genomes to the database (https://github.com/capsid/capsid/wiki/Tutorial#4-add-genomes-to-the-database) but it there is an error when trying to detect the GI number:
```
2020-02-19T10:51:17.972+0100 I NETWORK  [listener] connection accepted from 127.0.0.1:33546 #5 (1 connection now open)
10:51:17 Scanning GenBank File viral.1.genomic.gbff
10:51:18 KeyError: 'gi'
2020-02-19T10:51:18.057+0100 I NETWORK  [conn5] end connection 127.0.0.1:33546 (0 connections now open)
```
This error occurs with the latest RefSeq viral GenBank files and it appears that the .gbff files do not include a GenInfo (GI) Identifier.

GenBank files from tutorial
```
LOCUS       NC_000011          135006516 bp    DNA     linear   CON 25-OCT-2010
DEFINITION  Homo sapiens chromosome 11, GRCh37.p2 primary reference assembly.
ACCESSION   NC_000011 GPC_000000035
VERSION     NC_000011.9  GI:224589802
DBLINK      Project: 168
```

GenBank files from latest RefSeq release
```
LOCUS       NC_001798             154675 bp    DNA     linear   VRL 16-MAY-2016
DEFINITION  Human herpesvirus 2 strain HG52, complete genome.
ACCESSION   NC_001798
VERSION     NC_001798.2
DBLINK      BioProject: PRJNA15218
KEYWORDS    RefSeq.
SOURCE      Human alphaherpesvirus 2 (Herpes simplex virus 2)
```

Is there a way to gather the latest viral GenBank files that include this information or can we only use the provided older viral genomes?

**Comment by iborozan** [comment]
the capsid pipeline is currently not under active development and can only process older GenBank files that contain gi identifiers for now.
